### ISSUE TITLE
Splint Shell

### ISSUE THREAD

**Issue by Guisan** [patmo141/d3guard#5]
New issue.
![screenshot 35](https://user-images.githubusercontent.com/17667365/34439592-4f0ecee4-ecaf-11e7-9248-1d6de9185bbf.png)

**Comment by patmo141** [comment]
is this version v0.1.5?  I'm re-working the offsets to get them  more accuate, please revert to v0.1.4 for the time being.  Apologies this bug slipped in

**Comment by Guisan** [comment]
Yes, it's version v0.1.5. I'm curious to try out the new features.

**Comment by patmo141** [comment]
this should be fixed now in v0.1.6
